name: linter-check
on: push
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
       - uses: actions/checkout@v2
       - name: npm install
         run: | 
           make install
        - name: Test & publish code coverage
              # Publish code coverage on Code Climate
              # https://github.com/paambaati/codeclimate-action
          uses: paambaati/codeclimate-action@v2.7.4
                # Add Code Climate secret key
          env:
            CODECLIMATE_KEY: ${{ secrets.CODECLIMATE_KEY }}
          with:
            coverageCommand: make test-coverage
            debug: true

           